### ISSUE TITLE
Program freezes when trying to map guitar 

### ISSUE THREAD

**Issue by Joyconnizant** [InvoxiPlayGames/FestivalInstrumentMapper#23]
So i'm using a pi pico guitar set to PS3 mode in guitar configurator, and whenever i try to map the guitar the program freezes for a few minutes and then shows me an error that says this, is there any way to fix this? System.Exception: Failed to remove synthetic controller. (HRESULT: 80004004)
   at FestivalInstrumentMapper.SyntheticController.Dispose(Boolean disposing) in C:\Users\Emma\Code\FestivalInstrumentMapper\Native\SyntheticController.cs:line 31
   at FestivalInstrumentMapper.SyntheticController.Finalize() in C:\Users\Emma\Code\FestivalInstrumentMapper\Native\SyntheticController.cs:line 18

**Comment by sanjay900** [comment]
I have no idea why that would cause it to freeze, is it set to ps3 gh or ps3 rb?
